---
#
# Playbook to install the ELK stack
#
- hosts: all
  remote_user: vagrant 
  become: yes
  become_method: sudo
  roles:
    - { role: java }
    - { role: elasticsearch }
    - { role: kibana }
